### ISSUE TITLE
HarvestApi Object can't be used after refreshing

### ISSUE THREAD

**Issue by KelseySheely** [cogitools/hapi#6]
After refreshing a token, the $refreshingToken variable is not reset and since it is protected, it cannot be changed by the user. This makes all subsequent calls use the refresh url. The object cannot be used for further calls so must be re-instantiated by the calling script.

Set $refreshingToken = null after running the refresh token POST inside of the refreshToken() method.

**Comment by ahuggins** [comment]
I think this resolves it: https://github.com/cogitools/hapi/pull/7

just merged it in.
